apiVersion: v1
kind: Service
metadata:
  name: {{ include "joke-generator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "joke-generator.labels" . | nindent 4 }}
spec:
  selector:
    app: joke-generator
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
